blank_issues_enabled: false
contact_links:
  - name: VoiceLog Community Discussions
    url: https://github.com/Cod-e-Codes/voicelog/discussions
    about: Ask questions and discuss VoiceLog with the community
