name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
    
    - name: Install PortAudio dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libportaudio2 portaudio19-dev
    
    - name: Build Linux Binary
      run: |
        go build -ldflags="-X main.version=${{ github.ref_name }}" -o voicelog-linux-amd64 main.go
        tar -czf voicelog-${{ github.ref_name }}-linux-amd64.tar.gz voicelog-linux-amd64 README.md LICENSE
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 1
    
    - name: Upload Linux Release Asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: voicelog-${{ github.ref_name }}-linux-amd64.tar.gz
        draft: false
        prerelease: false
